"""Phase 4 session preflight, durable consumption and non-resumable execution."""
from __future__ import annotations
from dataclasses import dataclass,asdict
import os
from pathlib import Path
import re
import stat

from phase3.identity import raw_sha256,canonical_bytes,canonical_sha256
from .boundary import (WorkspaceAuthorization,DirectoryBinding,create_session_directory,
    create_attempt_directory,batch_id,inspect_directory,BoundaryError)
from .contracts import ContractError,JsonSnapshot,SPEC_SHA256,parse_json
from .derivation import BASELINE_SOURCES
from .runner import (ApprovedInputs,prepare_input,load_frozen_plan,closed,digest,
                     initialize_attempt,evaluate_once,_issued_permits)
from .evidence import EvidenceWriter,INVENTORY,ALLOWED
from .verification import verify_attempt,compare_attempts

CONTROL_NAMES=("plan","manifest","procedure","workspace","preflight","human_go")

@dataclass(frozen=True,slots=True)
class ControlExpectation:
    """Operator-supplied trust anchors; not generated by preflight from inputs."""
    hashes: tuple[tuple[str,str],...]
    code_head: str

    def __post_init__(self):
        entries=tuple(tuple(e) for e in self.hashes)
        if len(entries)!=6 or {e[0] for e in entries}!=set(CONTROL_NAMES):
            raise ContractError("six external control identities required")
        for name,value in entries:digest(value)
        if type(self.code_head) is not str or re.fullmatch("[0-9a-f]{40}",self.code_head) is None:
            raise ContractError("code HEAD identity required")
        object.__setattr__(self,"hashes",entries)

@dataclass(frozen=True,slots=True,eq=False)
class CheckedSession:
    authorization: WorkspaceAuthorization
    plan: object
    approved: ApprovedInputs
    prepared: tuple
    binding: JsonSnapshot
    expected: ControlExpectation

_checked={}
def preflight(control_bytes,expected,authorization,source_bytes,*,current_head,inspection_only=False):
    if type(expected) is not ControlExpectation or type(authorization) is not WorkspaceAuthorization:
        raise ContractError("external control/workspace authorization required")
    if set(control_bytes)!=set(CONTROL_NAMES) or current_head!=expected.code_head:
        raise ContractError("control set or current code HEAD mismatch")
    hashes=dict(expected.hashes)
    docs={}
    for name in CONTROL_NAMES:
        if type(control_bytes[name]) is not bytes or raw_sha256(control_bytes[name])!=hashes[name]:
            raise ContractError(f"control raw identity mismatch: {name}")
        docs[name]=parse_json(control_bytes[name])
    approved=ApprovedInputs(control_bytes["manifest"],hashes["manifest"])
    plan=load_frozen_plan(control_bytes["plan"],hashes["plan"])
    plan_doc=docs["plan"]
    if plan_doc["manifest_sha256"]!=hashes["manifest"]:raise ContractError("plan/manifest mismatch")
    procedure=docs["procedure"]
    closed(procedure,("schema_id","procedure_id","frozen_spec_sha256","no_retry","claim_boundary"))
    if (procedure["schema_id"]!="P4-PROCEDURE-v1" or procedure["frozen_spec_sha256"]!=SPEC_SHA256
            or procedure["no_retry"] is not True or procedure["claim_boundary"]!="SIMULATION_LIMITED"
            or type(procedure["procedure_id"]) is not str or not procedure["procedure_id"]):
        raise ContractError("procedure contract mismatch")
    workspace=docs["workspace"]
    closed(workspace,("schema_id","authorization_id","root","protected_roots","procedure_sha256"))
    workspace_expected={"schema_id":"P4-WORKSPACE-AUTH-v1","authorization_id":authorization.authorization_id,
        "root":str(authorization.root),"protected_roots":[str(p) for p in authorization.protected_roots],
        "procedure_sha256":hashes["procedure"]}
    if workspace!=workspace_expected:raise ContractError("workspace control binding mismatch")
    common={"code_head":current_head,"plan_sha256":hashes["plan"],"manifest_sha256":hashes["manifest"],
        "workspace_sha256":hashes["workspace"],"procedure_sha256":hashes["procedure"]}
    expected_preflight={"schema_id":"P4-PREFLIGHT-v1","status":"PASS",**common}
    if docs["preflight"]!=expected_preflight:raise ContractError("preflight control binding mismatch")
    expected_go={"schema_id":"P4-HUMAN-GO-v1","decision":"APPROVED","session_id":plan_doc["session_id"],
                 "preflight_sha256":hashes["preflight"],**common}
    if docs["human_go"]!=expected_go:raise ContractError("Human GO binding mismatch")
    if len(plan.slots)!=42 or len({s.slot_id for s in plan.slots})!=42:raise ContractError("42 unique slots required")
    prepared=tuple(prepare_input(c.case_id,{n:source_bytes[n] for n in BASELINE_SOURCES[c.source_baseline_id]},approved) for c in plan.cases)
    inspect_directory(authorization.root)
    target=authorization.root/plan_doc["session_id"]
    try:
        os.lstat(target)
    except FileNotFoundError:
        pass
    else:
        if not inspection_only:
            raise ContractError("started/partial/completed session cannot be reused")
    binding={"session_id":plan_doc["session_id"],"plan_sha256":hashes["plan"],
        "human_go_sha256":hashes["human_go"],"code_head":current_head,
        "manifest_sha256":hashes["manifest"],"workspace_authorization_id":authorization.authorization_id,
        "ordered_slots_sha256":canonical_sha256([s.slot_id for s in plan.slots],exclude_volatile=False),
        "procedure_sha256":hashes["procedure"],"preflight_sha256":hashes["preflight"]}
    checked=CheckedSession(authorization,plan,approved,prepared,JsonSnapshot.of(binding),expected)
    if not inspection_only:
        _checked[id(checked)]=checked
    return checked

def dry_plan(checked):
    if type(checked) is not CheckedSession:raise ContractError("checked session required")
    return {"slots":[asdict(slot) for slot in checked.plan.slots],"standard_attempt_count":42,
            "hard_max":60,"governance_call_count":0}

def _new_json(path,value):
    raw=canonical_bytes(value,exclude_volatile=False)
    with path.open("xb") as f:f.write(raw);f.flush();os.fsync(f.fileno())
    if path.read_bytes()!=raw:raise ContractError("session artifact read-back mismatch")
    return raw_sha256(raw)

def _safe_session_file(path):
    inspect_directory(path.parent)
    info=os.lstat(path)
    if not stat.S_ISREG(info.st_mode) or info.st_file_attributes & stat.FILE_ATTRIBUTE_REPARSE_POINT:
        raise BoundaryError("unsafe session record")
    return path.read_bytes()

def validate_session_tree(checked,root):
    allowed_files={"session_start.json","session_result.json","session_inventory.json"}
    allowed_dirs=set()
    for slot in checked.plan.slots:
        prefix=f"{slot.batch_id}/{slot.case_id}/attempt-{slot.attempt_number:02}"
        for leaf in ALLOWED:
            relative=prefix+"/"+leaf
            allowed_files.add(relative)
            parent=Path(relative).parent
            while str(parent)!=".":
                allowed_dirs.add(parent.as_posix());parent=parent.parent
    for current,dirs,files in os.walk(root,followlinks=False):
        for name in dirs:
            path=Path(current)/name
            if path.relative_to(root).as_posix() not in allowed_dirs:
                raise BoundaryError("unexpected session directory")
            inspect_directory(path)
        for name in files:
            path=Path(current)/name
            if path.relative_to(root).as_posix() not in allowed_files:
                raise BoundaryError("unexpected session artifact")
            _safe_session_file(path)

def inspect_session(checked):
    """Read-only inspector; incomplete started sessions never authorize continuation."""
    root=checked.authorization.root/checked.binding.value["session_id"]
    try:os.lstat(root)
    except FileNotFoundError:
        return {"status":"NOT_STARTED","slot_statuses":{s.slot_id:"NOT_STARTED" for s in checked.plan.slots},"resumable":False}
    inspect_directory(root)
    try:validate_session_tree(checked,root)
    except (OSError,ValueError):
        return {"status":"STOPPED_CRASH_OR_INCOMPLETE_ATTEMPT",
                "slot_statuses":{s.slot_id:"EXECUTION_STATUS_INDETERMINATE" for s in checked.plan.slots},
                "resumable":False}
    statuses={}
    for slot in checked.plan.slots:
        path=root/slot.batch_id/slot.case_id/f"attempt-{slot.attempt_number:02}"
        try:os.lstat(path)
        except FileNotFoundError:statuses[slot.slot_id]="NOT_RUN_AFTER_STOP";continue
        inspect_directory(path)
        statuses[slot.slot_id]="EXECUTION_STATUS_INDETERMINATE"
        try:
            marker=parse_json(_safe_session_file(path/"00_spec"/"attempt_start.json"))
            if (marker["slot_id"]!=slot.slot_id or marker["session_binding"]!=checked.binding.value):
                continue
            if (path/INVENTORY).exists():
                verify_attempt(path,checked.approved)
                statuses[slot.slot_id]="COMPLETED"
        except (OSError,ValueError,KeyError,TypeError):
            pass
    status="STOPPED_CRASH_OR_INCOMPLETE_ATTEMPT"
    try:
        start=parse_json(_safe_session_file(root/"session_start.json"))
        terminal=parse_json(_safe_session_file(root/"session_result.json"))
        inventory=parse_json(_safe_session_file(root/"session_inventory.json"))
        if start!=checked.binding.value:raise ContractError("session start mismatch")
        if terminal["session_binding"]!=checked.binding.value:raise ContractError("session terminal binding mismatch")
        if (inventory["session_start_sha256"]!=raw_sha256(_safe_session_file(root/"session_start.json"))
                or inventory["session_result_sha256"]!=raw_sha256(_safe_session_file(root/"session_result.json"))):
            raise ContractError("session inventory mismatch")
        if terminal["status"]=="COMPLETED" and all(v=="COMPLETED" for v in statuses.values()):
            if terminal["governance_call_count"]!=42 or len(inventory["attempt_inventories"])!=42:
                raise ContractError("session count mismatch")
            for slot,entry in zip(checked.plan.slots,inventory["attempt_inventories"]):
                if entry["slot_id"]!=slot.slot_id:raise ContractError("session inventory slot mismatch")
                path=root/slot.batch_id/slot.case_id/f"attempt-{slot.attempt_number:02}"
                verify_attempt(path,checked.approved,entry["sha256"])
            status="COMPLETED"
        elif terminal["status"]=="STOPPED_RUNTIME_OR_VERIFICATION":
            status=terminal["status"]
    except (OSError,ValueError,KeyError,TypeError):
        pass
    return {"status":status,"slot_statuses":statuses,"resumable":False}

def run_session(checked,*,_fault_hook=None):
    """Execute the approved 42 slots; the first failure terminates the session.

    _fault_hook exists solely for bounded development fault/crash injection.
    It receives A-G at their frozen crash windows; no governance callback exists.
    """
    if _checked.get(id(checked)) is not checked:raise ContractError("issued preflight required")
    hook=_fault_hook or (lambda window:None)
    hook("A")
    session=create_session_directory(checked.authorization,checked.binding.value["session_id"])
    _new_json(session.directory.path/"session_start.json",checked.binding.value)
    hook("B")
    statuses={s.slot_id:"NOT_RUN_AFTER_STOP" for s in checked.plan.slots}
    count=0;inventories=[];previous={};failure=None
    for slot in checked.plan.slots:
        writer=None;permit=None;counted=False
        try:
            session.validate()
            prepared=next(p for p in checked.prepared if p.case.case_id==slot.case_id)
            attempt=create_attempt_directory(session,slot.case_id,slot.attempt_number)
            statuses[slot.slot_id]="EXECUTION_STATUS_INDETERMINATE"
            hook("C")
            permit=initialize_attempt(prepared,attempt,checked.binding.value)
            hook("D")
            writer=EvidenceWriter(permit);writer.persist_pre_evaluation()
            # E is injected inside governance by the crash-worker test, not before this call.
            result=evaluate_once(permit)
            count+=1;counted=True
            hook("F")
            writer.persist_result(result)
            hook("G")
            writer.reconcile_and_finalize()
            verify_attempt(attempt.directory.path,checked.approved)
            if slot.case_id in previous:compare_attempts(previous[slot.case_id],attempt.directory.path,checked.approved)
            previous[slot.case_id]=attempt.directory.path
            inventories.append({"slot_id":slot.slot_id,"sha256":raw_sha256((attempt.directory.path/INVENTORY).read_bytes())})
            statuses[slot.slot_id]="COMPLETED"
        except Exception as exc:
            if permit is not None and not counted and _issued_permits.get(id(permit),(None,False))[1]:
                count+=1
            failure={"slot_id":slot.slot_id,"error":repr(exc)}
            if writer is not None and writer.phase!="FINALIZED":
                try:writer.record_failure(repr(exc))
                except Exception as write_exc:failure["recording_error"]=repr(write_exc)
            statuses[slot.slot_id]="STOPPED_RUNTIME_OR_VERIFICATION"
            break
    try:validate_session_tree(checked,session.directory.path)
    except (OSError,ValueError) as exc:
        if failure is None:failure={"slot_id":None,"error":repr(exc)}
        else:failure["boundary_error"]=repr(exc)
    status="COMPLETED" if failure is None and count==42 and all(s=="COMPLETED" for s in statuses.values()) else "STOPPED_RUNTIME_OR_VERIFICATION"
    result={"schema_id":"P4-SESSION-RESULT-v1","status":status,"session_binding":checked.binding.value,
            "slot_statuses":statuses,"governance_call_count":count,"retry_count":0,
            "standard_attempt_count":42,"hard_max":60,"failure":failure,"claim_boundary":"SIMULATION_LIMITED"}
    session.validate()
    result_hash=_new_json(session.directory.path/"session_result.json",result)
    _new_json(session.directory.path/"session_inventory.json",{"schema_id":"P4-SESSION-INVENTORY-v1",
        "session_start_sha256":raw_sha256((session.directory.path/"session_start.json").read_bytes()),
        "session_result_sha256":result_hash,"attempt_inventories":inventories})
    return JsonSnapshot.of(result)
